### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by lukamac** [pulp-platform/pulp-nn-mixed#3]
https://github.com/pulp-platform/pulp-nn-mixed/blob/aeb5e15a12bb6c1ea141a9191782f3d264f3d90a/XpulpV2/32bit/src/MatrixMultiplication/pulp_nn_matmul_i8_i8_i8.c#L120-L121

It should be `int8_t` not `uint8_t` for inB and inB2.

**Comment by AlessandroNadalini** [comment]
- Fixed template in commit [950ff06](https://github.com/pulp-platform/pulp-nn-mixed/commit/950ff06db47b0bca85ca49399d07e8a1d6d11123)
- Generated kernels with bug fix at [0439604](https://github.com/pulp-platform/pulp-nn-mixed/commit/04396041f480d59d80d15ceed240787f6d6b7a10)
